;<?php
;die(); // For further security
;/*

;language table
;sosere enterprise edition
;@author: Arthur Kaiser <sosere@sosere.com>


[languages]
af = "Afrikaans"
ar = "Arabic"
az = "Azeri"
be = "Belarusian"
bg = "Bulgarian"
bs = "Bosnian"
ca = "Catalan"
cs = "Czech"
cy = "Welsh"
da = "Danish"
de = "German"
dv = "Divehi"
el = "Greek"
en = "English"
es = "Spanish"
et = "Estonian"
eu = "Basque"
fa = "Farsi"
fi = "Finnish"
fr = "French"
gu = "Gujarati"
he = "Hebrew"
hi = "Hindi"
hr = "Croatian "
hu = "Hungarian"
hy = "Armenian"
id = "Indonesian"
is = "Icelandic"
it = "Italian"
ja = "Japanese"
ka = "Georgian"
kk = "Kazakh"
kn = "Kannada"
ko = "Korean"
ky = "Kyrgyz"
lt = "Lithuanian"
lv = "Latvian"
mi = "Maori"
mr = "Marathi"
ms = "Malay"
mt = "Maltese"
nb = "Norwegian"
nl = "Dutch "
ns = "Northern Sotho"
pa = "Punjabi"
pl = "Polish"
ps = "Pashto"
pt = "Portuguese"
qu = "Quechua"
ro = "Romanian"
ru = "Russian"
sa = "Sanskrit "
se = "Sami"
sk = "Slovak"
sl = "Slovenian"
sq = "Albanian"
sr = "Serbian"
sv = "Swedish"
sw = "Swahili"
ta = "Tamil"
te = "Telugu"
th = "Thai"
tl = "Tagalog"
tn = "Tswana"
tr = "Turkish"
uz = "Uzbek (Latin)"
vi = "Vietnamese"
zh = "Chinese"
zu = "Zulu"

;*/

;?>